version: "3.9"
services:
  marusia-php-fpm:
    build:
      dockerfile: ./Docker/fpm/Dockerfile
      context: .
    volumes:
      - .:/app
  marusia-nginx:
    build:
      dockerfile: ./Docker/nginx/Dockerfile
      context: .
    ports:
      - "8080:80"
  marusia-workspace:
    build:
      dockerfile: ./Docker/workspace/Dockerfile
      context: .
    volumes:
      - .:/app
